### ISSUE TITLE
Replace JAXP with StAX

### ISSUE THREAD

**Issue by weisJ** [weisJ/jsvg#37]
Instead of always using the XML loader from `javax.xml` allow specification of a different "driver", for the loading process. This way consumers of the library, which want to use a different implementation, don't have to replicate all of the logic from `SVGLoader`.

@develar Would this helpful for your fork?

**Comment by develar** [comment]
I think that Stax should replace a SAX parser in this library.

https://docs.oracle.com/cd/E19316-01/819-3669/bnbea/index.html

> StAX-enabled clients are generally easier to code than SAX clients. While it can be argued that SAX parsers are marginally easier to write, StAX parser code can be smaller and the code necessary for the client to interact with the parser simpler.

It was unclear if JSVG is a way to go. That's why it is in a fork, and that's why PR is not opened. Without your help, I cannot fix magic issues with filters and others that you fixed last month. I mean, I can try to fix it, but the goal is to use a ready-to-use good library and not reinvent the wheel.

For example, CSS was not supported initially by JSVG. Still, it was a ready hacky solution for SKIA, that was not suitable for everyone and cannot be in a generic library, but it suits our needs. And it was a part of STAX-based document builder in my fork.

So, when all issues with SVG rendering will be fixed and will be made a final decision that we use JSVG and not return to batik, I will try to get rid of my fork (open required PR).

**Comment by weisJ** [comment]
> think that Stax should replace a SAX parser in this library.
> [docs.oracle.com/cd/E19316-01/819-3669/bnbea/index.html](https://docs.oracle.com/cd/E19316-01/819-3669/bnbea/index.html)

I looked into it and support it.
